# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1422, 851)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(-10, -50, 1431, 801))
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1422, 20))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(58, 90))
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 90))
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.pbSetting = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pbSetting.setGeometry(QtCore.QRect(0, 0, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pbSetting.setFont(font)
        self.pbSetting.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/settings.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbSetting.setIcon(icon1)
        self.pbSetting.setIconSize(QtCore.QSize(64, 64))
        self.pbSetting.setObjectName("pbSetting")
        self.pbMon = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pbMon.setGeometry(QtCore.QRect(70, 0, 70, 70))
        self.pbMon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/mon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbMon.setIcon(icon2)
        self.pbMon.setIconSize(QtCore.QSize(64, 64))
        self.pbMon.setObjectName("pbMon")
        self.pbHelp = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pbHelp.setGeometry(QtCore.QRect(160, 0, 70, 70))
        self.pbHelp.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/help.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pbHelp.setIcon(icon3)
        self.pbHelp.setIconSize(QtCore.QSize(64, 64))
        self.pbHelp.setObjectName("pbHelp")
        self.lcdJam = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdJam.setGeometry(QtCore.QRect(260, 2, 71, 61))
        self.lcdJam.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdJam.setDigitCount(2)
        self.lcdJam.setProperty("intValue", 23)
        self.lcdJam.setObjectName("lcdJam")
        self.lcdMenit = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdMenit.setGeometry(QtCore.QRect(340, 0, 71, 61))
        self.lcdMenit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdMenit.setDigitCount(2)
        self.lcdMenit.setProperty("intValue", 23)
        self.lcdMenit.setObjectName("lcdMenit")
        self.lcdDetik = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdDetik.setGeometry(QtCore.QRect(420, 0, 71, 61))
        self.lcdDetik.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdDetik.setDigitCount(2)
        self.lcdDetik.setProperty("intValue", 23)
        self.lcdDetik.setObjectName("lcdDetik")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(325, 10, 21, 51))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(405, 10, 21, 51))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setGeometry(QtCore.QRect(142, 0, 16, 71))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(240, 0, 16, 71))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tanggal = QtWidgets.QLabel(self.dockWidgetContents)
        self.tanggal.setGeometry(QtCore.QRect(510, -5, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.tanggal.setFont(font)
        self.tanggal.setObjectName("tanggal")
        self.lokasi = QtWidgets.QLabel(self.dockWidgetContents)
        self.lokasi.setGeometry(QtCore.QRect(920, -5, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lokasi.setFont(font)
        self.lokasi.setObjectName("lokasi")
        self.line_3 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(890, 0, 16, 71))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(490, 0, 16, 71))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Penggunaan = QtWidgets.QAction(MainWindow)
        self.action_Penggunaan.setObjectName("action_Penggunaan")
        self.action_Seting = QtWidgets.QAction(MainWindow)
        self.action_Seting.setObjectName("action_Seting")
        self.action_Monitor = QtWidgets.QAction(MainWindow)
        self.action_Monitor.setObjectName("action_Monitor")
        self.action_Keluar = QtWidgets.QAction(MainWindow)
        self.action_Keluar.setObjectName("action_Keluar")
        self.menu_File.addAction(self.action_Seting)
        self.menu_File.addAction(self.action_Monitor)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Keluar)
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_Penggunaan)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.action_Keluar.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Parking System"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.label.setText(_translate("MainWindow", ":"))
        self.label_2.setText(_translate("MainWindow", ":"))
        self.tanggal.setText(_translate("MainWindow", "01/01/2019"))
        self.lokasi.setText(_translate("MainWindow", "Metro Mall"))
        self.action_About.setText(_translate("MainWindow", "&About (F12)"))
        self.action_Penggunaan.setText(_translate("MainWindow", "&Penggunaan (F1)"))
        self.action_Seting.setText(_translate("MainWindow", "&Seting (F2)"))
        self.action_Monitor.setText(_translate("MainWindow", "&Monitor (F3)"))
        self.action_Keluar.setText(_translate("MainWindow", "&Keluar"))

from . import form_src_rc
