# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MonitorForm(object):
    def setupUi(self, MonitorForm):
        MonitorForm.setObjectName("MonitorForm")
        MonitorForm.resize(1310, 850)
        MonitorForm.setMinimumSize(QtCore.QSize(1310, 850))
        self.tabWidget = QtWidgets.QTabWidget(MonitorForm)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1301, 841))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.groupBox = QtWidgets.QGroupBox(self.tab1)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 321))
        self.groupBox.setObjectName("groupBox")
        self.customerInfo = QtWidgets.QTextEdit(self.groupBox)
        self.customerInfo.setGeometry(QtCore.QRect(0, 20, 281, 301))
        self.customerInfo.setObjectName("customerInfo")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 350, 851, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plat_out = QtWidgets.QLabel(self.groupBox_2)
        self.plat_out.setGeometry(QtCore.QRect(20, 30, 791, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(72)
        self.plat_out.setFont(font)
        self.plat_out.setAlignment(QtCore.Qt.AlignCenter)
        self.plat_out.setObjectName("plat_out")
        self.plat_in = QtWidgets.QLineEdit(self.groupBox_2)
        self.plat_in.setGeometry(QtCore.QRect(90, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plat_in.setFont(font)
        self.plat_in.setObjectName("plat_in")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 59, 15))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 10, 561, 321))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cam = QtWidgets.QLabel(self.groupBox_3)
        self.cam.setGeometry(QtCore.QRect(0, 20, 561, 301))
        self.cam.setScaledContents(True)
        self.cam.setObjectName("cam")
        self.pbEmergency = QtWidgets.QPushButton(self.tab1)
        self.pbEmergency.setGeometry(QtCore.QRect(750, 550, 111, 23))
        self.pbEmergency.setObjectName("pbEmergency")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 600, 851, 191))
        self.groupBox_6.setObjectName("groupBox_6")
        self.plat_out_2 = QtWidgets.QLabel(self.groupBox_6)
        self.plat_out_2.setGeometry(QtCore.QRect(20, 30, 801, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(72)
        self.plat_out_2.setFont(font)
        self.plat_out_2.setAlignment(QtCore.Qt.AlignCenter)
        self.plat_out_2.setObjectName("plat_out_2")
        self.plat_in_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.plat_in_2.setGeometry(QtCore.QRect(120, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plat_in_2.setFont(font)
        self.plat_in_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plat_in_2.setObjectName("plat_in_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(270, 160, 91, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_7.setGeometry(QtCore.QRect(890, 10, 391, 781))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 30, 351, 231))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.slotR2 = QtWidgets.QLCDNumber(self.groupBox_8)
        self.slotR2.setGeometry(QtCore.QRect(0, 40, 351, 191))
        self.slotR2.setDigitCount(4)
        self.slotR2.setProperty("intValue", 999)
        self.slotR2.setObjectName("slotR2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 530, 351, 241))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.slotR4res = QtWidgets.QLCDNumber(self.groupBox_9)
        self.slotR4res.setGeometry(QtCore.QRect(0, 40, 351, 201))
        self.slotR4res.setDigitCount(4)
        self.slotR4res.setProperty("intValue", 999)
        self.slotR4res.setObjectName("slotR4res")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 280, 351, 231))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.slotR4 = QtWidgets.QLCDNumber(self.groupBox_10)
        self.slotR4.setGeometry(QtCore.QRect(0, 40, 351, 191))
        self.slotR4.setDigitCount(4)
        self.slotR4.setProperty("intValue", 999)
        self.slotR4.setObjectName("slotR4")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 251, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pbBukaPortal = QtWidgets.QPushButton(self.groupBox_4)
        self.pbBukaPortal.setGeometry(QtCore.QRect(20, 30, 80, 23))
        self.pbBukaPortal.setObjectName("pbBukaPortal")
        self.pbTutupPortal = QtWidgets.QPushButton(self.groupBox_4)
        self.pbTutupPortal.setGeometry(QtCore.QRect(20, 60, 80, 23))
        self.pbTutupPortal.setObjectName("pbTutupPortal")
        self.pbTest = QtWidgets.QPushButton(self.groupBox_4)
        self.pbTest.setGeometry(QtCore.QRect(20, 90, 80, 23))
        self.pbTest.setObjectName("pbTest")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 210, 1281, 601))
        self.groupBox_5.setObjectName("groupBox_5")
        self.dbgConsole = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.dbgConsole.setGeometry(QtCore.QRect(0, 20, 1281, 571))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.dbgConsole.setPalette(palette)
        self.dbgConsole.setObjectName("dbgConsole")
        self.tabWidget.addTab(self.tab2, "")

        self.retranslateUi(MonitorForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MonitorForm)

    def retranslateUi(self, MonitorForm):
        _translate = QtCore.QCoreApplication.translate
        MonitorForm.setWindowTitle(_translate("MonitorForm", "Monitoring Dashboard"))
        self.groupBox.setTitle(_translate("MonitorForm", "Informasi Pelanggan"))
        self.groupBox_2.setTitle(_translate("MonitorForm", "NoPol"))
        self.plat_out.setText(_translate("MonitorForm", "L 1000 ABC"))
        self.plat_in.setText(_translate("MonitorForm", "L1000ABC"))
        self.label_2.setText(_translate("MonitorForm", "Koreksi:"))
        self.groupBox_3.setTitle(_translate("MonitorForm", "Kamera"))
        self.cam.setText(_translate("MonitorForm", "TextLabel"))
        self.pbEmergency.setText(_translate("MonitorForm", "Emergency (F10)"))
        self.groupBox_6.setTitle(_translate("MonitorForm", "Tarif (dalam Rupiah)"))
        self.plat_out_2.setText(_translate("MonitorForm", "100.000,-"))
        self.plat_in_2.setText(_translate("MonitorForm", "120"))
        self.label_3.setText(_translate("MonitorForm", "Durasi Parkir:"))
        self.label_4.setText(_translate("MonitorForm", "menit"))
        self.groupBox_7.setTitle(_translate("MonitorForm", "Informasi Area Parkir"))
        self.groupBox_8.setTitle(_translate("MonitorForm", "Slot Parkir R2 Tersedia"))
        self.groupBox_9.setTitle(_translate("MonitorForm", "Slot Reservasi Tersedia"))
        self.groupBox_10.setTitle(_translate("MonitorForm", "Slot Parkir R4 Tersedia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MonitorForm", "Kontrol Utama"))
        self.groupBox_4.setTitle(_translate("MonitorForm", "Kontrol Manual"))
        self.pbBukaPortal.setText(_translate("MonitorForm", "Buka Portal"))
        self.pbTutupPortal.setText(_translate("MonitorForm", "Tutup Portal"))
        self.pbTest.setText(_translate("MonitorForm", "Test Gambar"))
        self.groupBox_5.setTitle(_translate("MonitorForm", "Debugging"))
        self.dbgConsole.setPlainText(_translate("MonitorForm", "Apapun yang terjadi dengan sistem bisa diinformasikan dalam debug console ini!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MonitorForm", "Setting"))

